### ISSUE TITLE
build process failed in  jdk11 and maven3

### ISSUE THREAD

**Issue by zzsczz** [tambapps/fourier-transform-library#3]
i get error message 

[ERROR] D:\ebook\python_dsp\fourier-transform-library-master\src\main\java\com\tambapps\fft4j\fourier\fft_1d\CooleyTukeyRecursiveFFT.java:11: error: incorrect use of inline tag
[ERROR]  * @link from https://rosettacode.org/wiki/Fast_Fourier_transform
[ERROR]    ^
[ERROR] D:\ebook\python_dsp\fourier-transform-library-master\src\main\java\com\tambapps\fft4j\fourier\util\Padding.java:5: error: bad use of '>'
[ERROR]  * zero-padding => raise resolution
[ERROR]                  ^
[ERROR]
[ERROR] Command line was: C:\Java\jdk-11.0.11\bin\javadoc.exe @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'D:\ebook\python_dsp\fourier-transform-library-master\target\apidocs' dir.

**Comment by tambapps** [comment]
Hi, the problem should be solved now. I managed to install this project using Maven 3.8.6 and Java 17
